import './styles/styles.css'
import './styles/navbar.css'
import './styles/navbar1.css'
import './styles/header.css'
import './styles/scrolltop.css'
import './styles/footer.css'
import './styles/title.css'
import './styles/booking.css'
import './styles/section.css'
import './styles/loadmain.css'
import './styles/chefs.css'
import './styles/testimonials.css'
import './styles/gallery.css'
import './styles/services.css'
import './styles/menudetail.css'
import './styles/contacts.css'
import './styles/yandexgo.css'

import LoadPage from './components/LoadPage'
import ScrollTop from './components/ScrollTop'
import Navbar from './components/Navbar'
import Navbar1 from './components/navbar/navbar1'
import Footer from './components/footer/footer'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Navbar />
        <Navbar1 />
        {children}
        <Footer />
        <LoadPage />
        <ScrollTop />
      </body>
    </html>
  );
}