# Generated by Django 5.1.2 on 2024-10-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooks',
            old_name='age',
            new_name='skill',
        ),
    ]
