# Generated by Django 5.1.2 on 2024-10-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_home_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooks',
            name='description',
        ),
    ]
