# Generated by Django 5.1.2 on 2024-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_company_coordinate_alter_company_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='company',
            name='about_us',
            field=models.TextField(default='Test uchun'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
