# Generated by Django 5.1.2 on 2024-10-22 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_address_company_address1_company_about_us_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='phone',
            new_name='phone1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address2',
        ),
        migrations.AddField(
            model_name='company',
            name='phone2',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{9,13}$')]),
        ),
    ]
