# Generated by Django 5.1.2 on 2024-10-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
